// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSItyGadvrS0_pT3r-HTKM3cnNRtILo94',
    appId: '1:942823702844:web:5a11c734b90e2f23a59e39',
    messagingSenderId: '942823702844',
    projectId: 'satpura-hostel-app',
    authDomain: 'satpura-hostel-app.firebaseapp.com',
    storageBucket: 'satpura-hostel-app.appspot.com',
    measurementId: 'G-4V679K7D25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8l5D-S5LngWgHFcZMViiAa4xTT_qMQlo',
    appId: '1:942823702844:android:fad7de468c33d336a59e39',
    messagingSenderId: '942823702844',
    projectId: 'satpura-hostel-app',
    storageBucket: 'satpura-hostel-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5prvJOcyGITOWWsG-p7W1i0debis8U6Q',
    appId: '1:942823702844:ios:36abd7f8e0adcf40a59e39',
    messagingSenderId: '942823702844',
    projectId: 'satpura-hostel-app',
    storageBucket: 'satpura-hostel-app.appspot.com',
    iosBundleId: 'com.satpura.hostel',
  );
}
